services:
  angular-app:
    image: node:lts
    container_name: angular-dev-container
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    command: >
      bash -c "npm install -g npm@latest &&
               npm install -g @angular/cli@17 &&
               npm install &&
               ng serve --host 0.0.0.0"

volumes:
  node_modules: